-- RLS setup is now managed via Prisma migrations.
-- See: prisma/migrations/20260605220000_rls_tenant_isolation/migration.sql
--
-- This file is kept only as a reference for the required app role setup.
-- Run these commands ONCE in psql before deploying:
--
--   CREATE ROLE predia_app LOGIN PASSWORD 'change-me' NOBYPASSRLS;
--   GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO predia_app;
--   GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO predia_app;
--
-- Then set DATABASE_URL in .env to use the predia_app credentials (not postgres superuser).
-- Without NOBYPASSRLS, RLS policies are bypassed entirely.
