packages:
  - 'predia-api'
  - 'predia-front'
  - 'predia-website'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: set this to true or false
  prisma: true
  sharp: set this to true or false
  unrs-resolver: true
